Homework 7: Aksana Batyrova
AksanaBatyrova/python-auto pull request #3
Opened 2024-05-22 18:14 UTC by AksanaBatyrova

2024-05-23 19:42 UTC, Stml89 requested changes

2024-05-23 19:42 UTC, Stml89 commented on homework_7.py
> +first_guess = input('Make a guess: ')
user can enter not a unique number, string and 3 or 5 symbols

2024-05-23 19:42 UTC, Stml89 commented on homework_7.py
> +ANSWER = 2310
is it possible to generate a secret number before each game?

2024-05-23 19:42 UTC, Stml89 commented on homework_7.py
> +    return None
why do you want to return None?

2024-05-24 12:16 UTC, AksanaBatyrova commented on homework_7.py
> +    return None
it was the way to overcome this issue: https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/inconsistent-return-statements.html

2024-05-24 12:16 UTC, AksanaBatyrova commented on homework_7.py
> +first_guess = input('Make a guess: ')
fixed in new commits

2024-05-24 12:17 UTC, AksanaBatyrova commented on homework_7.py
> +ANSWER = 2310
fixed in new commits

2024-05-28 20:06 UTC, Stml89 requested changes

2024-05-28 20:06 UTC, Stml89 commented on homework_7.py
> +        first_guess = int(input('Make a guess: '))
still possible to enter non unique number

2024-05-29 20:09 UTC, Stml89 requested changes

2024-05-29 20:09 UTC, Stml89 commented on homework_7.py
> +        first_guess = int(input('Make a guess: '))
But if you scroll a bit you find line #63, no checks there

2024-05-30 11:22 UTC, AksanaBatyrova commented on homework_7.py
> +        first_guess = int(input('Make a guess: '))
fixed

2024-05-31 19:04 UTC, Stml89 approved these changes

2024-06-01 07:56 UTC, merged