Homework8: Aksana Batyrova
AksanaBatyrova/python-auto pull request #4
Opened 2024-05-27 17:51 UTC by AksanaBatyrova

2024-05-31 19:12 UTC, Stml89 requested changes

2024-05-31 19:12 UTC, Stml89 commented on homework_8.py
> +print(solution([1, 2, 3]))
better to use assert to check that program works correctly

2024-05-31 19:12 UTC, Stml89 commented on homework_8.py
> +    return: int
Actually, the program returns float, not int

2024-05-31 19:12 UTC, Stml89 commented on homework_8.py
> +    n: integer
you have mentioned type, but not the porpoise, as you did in line #79

2024-05-31 19:12 UTC, Stml89 commented on homework_8.py
> +def validate(card_number: int):
what type are you going to return?

2024-06-02 08:49 UTC, AksanaBatyrova commented on homework_8.py
> +print(solution([1, 2, 3]))
fixed

2024-06-02 08:50 UTC, AksanaBatyrova commented on homework_8.py
> +    n: integer
fixed

2024-06-02 08:50 UTC, AksanaBatyrova commented on homework_8.py
> +def validate(card_number: int):
fixed

2024-06-02 15:18 UTC, AksanaBatyrova commented on homework_8.py
> +    return: int
fixed

2024-06-07 09:10 UTC, merged