Homework10: Aksana Batyrova
AksanaBatyrova/python-auto pull request #5
Opened 2024-06-03 12:43 UTC by AksanaBatyrova

HW for lection 10-Functions pt.2

2024-06-05 12:40 UTC, Eystei requested changes

2024-06-05 12:40 UTC, Eystei commented on homework_10.py
> +def solution(candles_number, make_new):
there is no need to carry out calculations in separate functions, complicates the code, adds unnecessary calls

![image](https://github.com/AksanaBatyrova/python-auto/assets/95315504/0c1c8975-7102-4714-8add-cae64e2e638a)

2024-06-06 10:17 UTC, AksanaBatyrova commented on homework_10.py
> +def solution(candles_number, make_new):
It was made on purpose. Clean code principles suggests using simple functions performing one action each instead of inserting all actions to one function. Probably, this task is not the case where this code style really make things, but I decided to try it anyway. 
https://testdriven.io/blog/clean-code-python/#functions

2024-06-06 10:29 UTC, Eystei commented on homework_10.py
> +def solution(candles_number, make_new):
Oh, it’s really nice that you used this principle, then everything is ok.

2024-06-06 10:29 UTC, AksanaBatyrova commented on homework_10.py
> +def strings_with_symbol(input_str: str):
removed type annotation

2024-06-06 10:29 UTC, AksanaBatyrova commented on homework_10.py
> +    return delete_elements(input_str) if '#' in input_str else ""
fixed

2024-06-06 10:30 UTC, AksanaBatyrova commented on homework_10.py
> +def count_letters(input_string):
fixed

2024-06-06 10:30 UTC, AksanaBatyrova commented on homework_10.py
> +        can_do = math.floor(leftovers / make_new)
fixed

2024-06-06 10:31 UTC, Eystei commented on homework_10.py
> +def strings_with_symbol(input_str: str):
+

2024-06-06 10:37 UTC, Eystei approved these changes
@Stml89  I have no more suggestions for improvement, looks like everything ok.

Probably I would like each task to be in its own file
Like this 
![image](https://github.com/AksanaBatyrova/python-auto/assets/95315504/c72d93c7-5eb9-47e8-ae94-769737a366ac)

2024-06-06 15:14 UTC, Stml89 approved these changes

2024-06-07 09:10 UTC, merged