Homework11: Aksana Batyrova
AksanaBatyrova/python-auto pull request #6
Opened 2024-06-05 10:59 UTC by AksanaBatyrova

HW 11-Decorator

2024-06-08 07:30 UTC, Stml89 requested changes

2024-06-08 07:30 UTC, Stml89 commented on homework_11.py
Please, use 1 file for 1 task

2024-06-08 07:30 UTC, Stml89 commented on homework_11.py
> +example_function(5, -4)
```suggestion
assert example_function(5, -4) == <expected value>
```

2024-06-08 07:30 UTC, Stml89 commented on homework_11.py
> +        return function
You are not calling `example_function` function, what you are doing here is just return function object
```suggestion
        return function(*args)
```

2024-06-08 07:30 UTC, Stml89 commented on homework_11.py
> +        return function
The same problem for task#2, task#3

2024-06-09 14:40 UTC, AksanaBatyrova commented on homework_11.py
> +example_function(5, -4)
This decorator throws exception if any of arguments passed to the function is negative, so my expected value is Value Error with some message in it. I haven't found the way how to assert exceptions, could you help, please?

2024-06-09 15:04 UTC, AksanaBatyrova commented on homework_11.py
> +        return function
fixed

2024-06-16 07:03 UTC, Stml89 approved these changes
In general PR looks good, fix last comment and you can merge it

2024-06-16 13:53 UTC, AksanaBatyrova commented on homework_11.py
> +example_function(5, -4)
fixed

2024-06-16 13:54 UTC, merged