Homework12: Aksana Batyrova
AksanaBatyrova/python-auto pull request #7
Opened 2024-06-12 02:23 UTC by AksanaBatyrova

HW 12 - OOP pt. 1

2024-06-16 16:38 UTC, Stml89 requested changes

2024-06-16 16:38 UTC, Stml89 commented on homework12/task1_library.py
> +    def take_book(self, cls):
`cls` is used with classmethod decorator, `self` is used in the class
https://www.geeksforgeeks.org/class-method-vs-static-method-python/

2024-06-16 16:38 UTC, Stml89 commented on homework12/task1_library.py
> +        self.reserved_book = reserved_book
```suggestion
        self.taken_book = None
        self.reserved_book = None
```

2024-06-16 16:38 UTC, Stml89 commented on homework12/task1_library.py
> +user2 = User("Jane", None, None)
```suggestion
user1 = User("John")
user2 = User("Jane")
```

2024-06-16 16:38 UTC, Stml89 commented on homework12/task2_bank_deposit.py
> +        return int(n*(1+0.1)**r)
use `round` insted

2024-06-16 16:38 UTC, Stml89 commented on homework12/task2_bank_deposit.py
> +    def deposit(self, n, r):
If the user puts 1000, for 1 year, with 10% -> expected to get ~1104.71

2024-06-16 16:38 UTC, Stml89 commented on homework12/task2_bank_deposit.py
> +class Deposit:
you are not using this class, if so pls remove it

2024-06-18 12:16 UTC, AksanaBatyrova commented on homework12/task1_library.py
> +user2 = User("Jane", None, None)
fixed

2024-06-18 12:16 UTC, AksanaBatyrova commented on homework12/task2_bank_deposit.py
> +        return int(n*(1+0.1)**r)
fixed

2024-06-18 12:16 UTC, AksanaBatyrova commented on homework12/task2_bank_deposit.py
> +    def deposit(self, n, r):
fixed

2024-06-18 12:17 UTC, AksanaBatyrova commented on homework12/task2_bank_deposit.py
> +class Deposit:
fixed

2024-06-19 19:19 UTC, AksanaBatyrova commented on homework12/task1_library.py
> +    def take_book(self, cls):
fixed

2024-06-21 19:47 UTC, Stml89 commented on homework12/task2_bank_deposit.py
> +    def deposit(self, n, r):
The customer wouldn’t be happy, because if she puts 1000, for 1 year, with 10% -> expected to get ~1104.71

2024-06-22 13:14 UTC, AksanaBatyrova commented on homework12/task2_bank_deposit.py
> +    def deposit(self, n, r):
fixed

2024-06-23 09:13 UTC, Stml89 approved these changes

2024-06-23 09:37 UTC, merged