Homework13: Aksana Batyrova
AksanaBatyrova/python-auto pull request #8
Opened 2024-06-16 17:18 UTC by AksanaBatyrova

HW 12 - OOP pt.2

2024-06-21 18:33 UTC, Stml89 requested changes

2024-06-21 18:33 UTC, Stml89 commented on homework13/task1_cards_deck.py
> +    def create_deck(self, cls):
`cls` is using for class methods https://medium.com/plain-simple-software/python-styling-cls-vs-self-ec141c28d6d4

```suggestion
    def create_deck(self, card):
```

2024-06-21 18:33 UTC, Stml89 commented on homework13/task1_cards_deck.py
> +    def create_deck(self, cls):
It can be done in `__init__` method

2024-06-21 18:33 UTC, Stml89 commented on homework13/task1_cards_deck.py
> +    def get_by_number(self, number):
`get` method should be related to the `CardsDeck` class

2024-06-21 18:33 UTC, Stml89 commented on homework13/task2_currency_converter.py
> +        pass
if you introduce this method, so pls use it

2024-06-21 18:33 UTC, Stml89 commented on homework13/task2_currency_converter.py
> +    def exchange_currency(self, sell, amount, buy='BYN'):
move it to `Currency` class

2024-06-22 14:01 UTC, AksanaBatyrova commented on homework13/task1_cards_deck.py
> +    def create_deck(self, cls):
fixed

2024-06-22 14:02 UTC, AksanaBatyrova commented on homework13/task1_cards_deck.py
> +    def create_deck(self, cls):
fixed

2024-06-22 14:02 UTC, AksanaBatyrova commented on homework13/task1_cards_deck.py
> +    def get_by_number(self, number):
fixed

2024-06-22 14:02 UTC, AksanaBatyrova commented on homework13/task2_currency_converter.py
> +        pass
fixed

2024-06-22 14:02 UTC, AksanaBatyrova commented on homework13/task2_currency_converter.py
> +    def exchange_currency(self, sell, amount, buy='BYN'):
fixed

2024-06-22 22:14 UTC, Stml89 requested changes

2024-06-22 22:14 UTC, Stml89 commented on homework13/task1_cards_deck.py
> +    #     return self.new_deck
remove it

2024-06-23 10:11 UTC, AksanaBatyrova commented on homework13/task1_cards_deck.py
> +    #     return self.new_deck
done

2024-06-27 20:19 UTC, Stml89 requested changes

2024-06-27 20:19 UTC, Stml89 commented on homework13/task1_cards_deck.py
> +            Card(number, suit)
will it create 4 Jokers? But, actually only 2 exists

2024-06-27 20:19 UTC, Stml89 commented on homework13/task2_currency_converter.py
> +class Bank:
Seems like you mossed functionality from previous HW(deposit)

2024-06-28 12:15 UTC, AksanaBatyrova commented on homework13/task1_cards_deck.py
> +            Card(number, suit)
fixed

2024-06-28 12:15 UTC, AksanaBatyrova commented on homework13/task2_currency_converter.py
> +class Bank:
fixed

2024-06-29 11:28 UTC, Stml89 commented on .github/workflows/ruff.yaml
> +          ruff check --output-format=github .
What is the porpoise for adding this?

2024-06-30 11:42 UTC, AksanaBatyrova commented on .github/workflows/ruff.yaml
> +          ruff check --output-format=github .
![image](https://github.com/AksanaBatyrova/python-auto/assets/83409383/65a963df-be17-4049-9a39-24e69f0ded7d)

2024-07-01 14:24 UTC, Stml89 approved these changes

2024-07-01 15:37 UTC, merged